### ISSUE TITLE
MxlsxClass.py文件执行报错，找不到pandas_simple.xlsx文件

### ISSUE THREAD

**Issue by lyj14736** [shenxiangzhuang/PythonDataAnalysis#9]
Traceback (most recent call last):
  File "E:/Python/2019.7.15/19_面向对象.py", line 143, in <module>
    Demo.get_fileinfo()
  File "E:/Python/2019.7.15/19_面向对象.py", line 21, in get_fileinfo
    self.wb = load_workbook(filename=self.filename)
  File "C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\openpyxl\reader\excel.py", line 311, in load_workbook
    data_only, keep_links)
  File "C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\openpyxl\reader\excel.py", line 126, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\openpyxl\reader\excel.py", line 98, in _validate_archive
============================== FILE INFO ==============================
    archive = ZipFile(filename, 'r')
  File "D:\Python_Edition\Python37\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'pandas_simple.xlsx'

**Comment by shenxiangzhuang** [comment]
代码是没有问题的。报错就是找不到文件，因为我这里测试是在Ubuntu下进行的，所以你在Windows运行要修改文件路径才可以。

**Comment by lyj14736** [comment]
已经找到问题了，书中没有标注前期创建文件更改sheet名词------------------ 原始邮件 ------------------
发件人: "XiangzhuangShen"<notifications@github.com>
发送时间: 2019年7月27日(星期六) 晚上6:46
收件人: "shenxiangzhuang/PythonDataAnalysis"<PythonDataAnalysis@noreply.github.com>;
抄送: "lyj14736"<1837178394@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [shenxiangzhuang/PythonDataAnalysis] MxlsxClass.py文件执行报错，找不到pandas_simple.xlsx文件 (#9)



代码是没有问题的。报错就是找不到文&#x4EF6;，因为我这里测试是在Ubuntu下进行的，所以你在Windows运行要修改文&#x4EF6;路径才可以。
 
&mdash;
